services:
  db:
    image: postgres:14.1-alpine
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "pg_isready", "-q", "-d", "postgres", "-U", "user"]
      timeout: 45s
      interval: 10s
      retries: 10
    environment:
      - POSTGRES_USER=user
      - POSTGRES_DB=carewallet
      - POSTGRES_PASSWORD=pwd
    ports:
      - "5434:5432"
    volumes:
      - ./backend/db/simulation:/docker-entrypoint-initdb.d/
volumes:
  db:
    driver: local
